default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 172.24.0.2
  username: root
  password: password_test
#  password: <%#= ENV['POSTGRES_PASSWORD'] %>
#  database: <%#= ENV['POSTGRES_DB'] %>
  database: root

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production